# Railway Configuration for AI Mafia - FIXED
[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build && npm run build:server"

[deploy]
startCommand = "npm run start:server"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = { NODE_ENV = "production" }

# Ensure public networking is enabled
[services.backend]
source = "."